2022-11-29 20:19:23,466 INFO    MainThread:13756 [wandb_setup.py:_flush():68] Configure stats pid to 13756
2022-11-29 20:19:23,466 INFO    MainThread:13756 [wandb_setup.py:_flush():68] Loading settings from C:\Users\ybria\.config\wandb\settings
2022-11-29 20:19:23,466 INFO    MainThread:13756 [wandb_setup.py:_flush():68] Loading settings from C:\Users\ybria\Documents\GitHub\music-generation\Diffusion-LM-main\Diffusion-LM-main\improved-diffusion\wandb\settings
2022-11-29 20:19:23,466 INFO    MainThread:13756 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-11-29 20:19:23,466 INFO    MainThread:13756 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': 'Diffusion-LM-main\\Diffusion-LM-main\\improved-diffusion\\scripts\\train.py', 'program': 'C:\\Users\\ybria\\Documents\\GitHub\\music-generation\\Diffusion-LM-main\\Diffusion-LM-main\\improved-diffusion\\scripts\\train.py'}
2022-11-29 20:19:23,474 INFO    MainThread:13756 [wandb_setup.py:_flush():68] Applying login settings: {'api_key': '***REDACTED***'}
2022-11-29 20:19:23,474 INFO    MainThread:13756 [wandb_init.py:_log_setup():476] Logging user logs to C:\Users\ybria\Documents\GitHub\music-generation\Diffusion-LM-main\Diffusion-LM-main\improved-diffusion\wandb\run-20221129_201923-2lscj2fc\logs\debug.log
2022-11-29 20:19:23,474 INFO    MainThread:13756 [wandb_init.py:_log_setup():477] Logging internal logs to C:\Users\ybria\Documents\GitHub\music-generation\Diffusion-LM-main\Diffusion-LM-main\improved-diffusion\wandb\run-20221129_201923-2lscj2fc\logs\debug-internal.log
2022-11-29 20:19:23,474 INFO    MainThread:13756 [wandb_init.py:init():516] calling init triggers
2022-11-29 20:19:23,474 INFO    MainThread:13756 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-11-29 20:19:23,474 INFO    MainThread:13756 [wandb_init.py:init():569] starting backend
2022-11-29 20:19:23,474 INFO    MainThread:13756 [wandb_init.py:init():573] setting up manager
2022-11-29 20:19:23,474 INFO    MainThread:13756 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-11-29 20:19:23,482 INFO    MainThread:13756 [wandb_init.py:init():580] backend started and connected
2022-11-29 20:19:23,482 INFO    MainThread:13756 [wandb_init.py:init():658] updated telemetry
2022-11-29 20:19:23,538 INFO    MainThread:13756 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-11-29 20:19:30,977 WARNING MsgRouterThr:13756 [router.py:message_loop():77] message_loop has been closed
2022-11-29 20:19:33,640 ERROR   MainThread:13756 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "C:\Users\ybria\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "C:\Users\ybria\anaconda3\lib\site-packages\wandb\sdk\wandb_init.py", line 697, in init
    result = handle.wait(
  File "C:\Users\ybria\anaconda3\lib\site-packages\wandb\sdk\lib\mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
